-- MySQL Script generated by MySQL Workbench
-- 01/07/15 15:47:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MWRData
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MWRData
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MWRData` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MWRData` ;

-- -----------------------------------------------------
-- Table `MWRData`.`MWInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInventory` (
  `InvRecordId` INT NOT NULL,
  `RecoHeaderId` INT NOT NULL,
  `RecoNum` VARCHAR(20) NULL COMMENT '回收计划单号',
  `CrateCode` VARCHAR(20) NULL COMMENT '货箱编号',
  `DepotCode` VARCHAR(20) NULL COMMENT '仓库编号',
  `Source` VARCHAR(45) NULL COMMENT '来源（医院）名称',
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL COMMENT '废品名称',
  `WasteCode` VARCHAR(20) NULL COMMENT '废品编号',
  `RecoWeight` FLOAT NULL COMMENT '回收重量',
  `InvWeight` FLOAT NULL COMMENT '库存重量',
  `PostWeight` FLOAT NULL COMMENT '出库重量',
  `RecoWSCode` VARCHAR(20) NULL,
  `RecoEmpyCode` VARCHAR(20) NULL,
  `RecoDate` DATETIME NULL,
  `PostDate` DATETIME NULL,
  `Status` VARCHAR(2) NULL COMMENT '当前库存状态',
  `InvAuthId` INT NULL,
  PRIMARY KEY (`InvRecordId`))
ENGINE = InnoDB
COMMENT = '库存表-记录当前库存信息，库存来源等';


-- -----------------------------------------------------
-- Table `MWRData`.`MWRecoverHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWRecoverHeader` (
  `RecoHeaderId` INT NOT NULL,
  `RecoNum` VARCHAR(20) NULL,
  `CarCode` VARCHAR(20) NULL,
  `DriverCode` VARCHAR(20) NULL,
  `InspectorCode` VARCHAR(20) NULL COMMENT '跟车员',
  `CrateQty` INT NULL,
  `RecoWSCode` VARCHAR(20) NULL,
  `RecoEmpyCode` VARCHAR(20) NULL,
  `StratDate` DATETIME NULL,
  `EndDate` DATETIME NULL,
  `OperateType` VARCHAR(2) NULL COMMENT '处理类型-1.回收入库 2.直接处置',
  `Status` VARCHAR(2) NULL,
  `CarDisId` INT NULL,
  PRIMARY KEY (`RecoHeaderId`))
ENGINE = InnoDB
COMMENT = '回收计划信息表-记录提交的回收计划 ';


-- -----------------------------------------------------
-- Table `MWRData`.`MWRecoverDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWRecoverDetail` (
  `RecoDtlId` INT NOT NULL,
  `RecoHeaderId` INT NULL,
  `CrateCode` VARCHAR(20) NULL,
  `RecoNum` VARCHAR(20) NULL,
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL,
  `WasteCode` VARCHAR(20) NULL,
  `RecoWeight` FLOAT NULL,
  `RecoDate` DATETIME NULL,
  `InvAuthId` INT NULL,
  `Status` VARCHAR(2) NULL,
  PRIMARY KEY (`RecoDtlId`))
ENGINE = InnoDB
COMMENT = '回收计划详情表-记录回收计划中包含的废品详情明细';


-- -----------------------------------------------------
-- Table `MWRData`.`MWInventoryTrack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInventoryTrack` (
  `InvTrackRecordId` INT NOT NULL,
  `PostHeaderId` INT NULL,
  `CrateCode` VARCHAR(20) NULL,
  `PostNum` VARCHAR(20) NULL,
  `DepotCode` VARCHAR(20) NULL COMMENT '仓库编号',
  `Source` VARCHAR(45) NULL,
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL,
  `WasteCode` VARCHAR(20) NULL,
  `InvWeight` FLOAT NULL COMMENT '提交重量',
  `PostWeight` FLOAT NULL COMMENT '真实重量',
  `PostWSCode` VARCHAR(20) NULL COMMENT '库存操作工作站编号',
  `PostEmpyCode` VARCHAR(20) NULL COMMENT '库存操作员工编号',
  `ReceiveDate` DATETIME NULL,
  `PostDate` DATETIME NULL,
  `Status` VARCHAR(2) NULL COMMENT '库存操作状态',
  `InvRecordId` INT NULL COMMENT '关联库存ID',
  `InvAuthId` INT NULL,
  PRIMARY KEY (`InvTrackRecordId`))
ENGINE = InnoDB
COMMENT = '库存跟踪表-记录每次出库库存操作信息，（现在是两个工作站）';


-- -----------------------------------------------------
-- Table `MWRData`.`MWInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInventory` (
  `InvRecordId` INT NOT NULL,
  `RecoHeaderId` INT NOT NULL,
  `RecoNum` VARCHAR(20) NULL COMMENT '回收计划单号',
  `CrateCode` VARCHAR(20) NULL COMMENT '货箱编号',
  `DepotCode` VARCHAR(20) NULL COMMENT '仓库编号',
  `Source` VARCHAR(45) NULL COMMENT '来源（医院）名称',
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL COMMENT '废品名称',
  `WasteCode` VARCHAR(20) NULL COMMENT '废品编号',
  `RecoWeight` FLOAT NULL COMMENT '回收重量',
  `InvWeight` FLOAT NULL COMMENT '库存重量',
  `PostWeight` FLOAT NULL COMMENT '出库重量',
  `RecoWSCode` VARCHAR(20) NULL,
  `RecoEmpyCode` VARCHAR(20) NULL,
  `RecoDate` DATETIME NULL,
  `PostDate` DATETIME NULL,
  `Status` VARCHAR(2) NULL COMMENT '当前库存状态',
  `InvAuthId` INT NULL,
  PRIMARY KEY (`InvRecordId`))
ENGINE = InnoDB
COMMENT = '库存表-记录当前库存信息，库存来源等';


-- -----------------------------------------------------
-- Table `MWRData`.`MWPostHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWPostHeader` (
  `PostHeaderId` INT NOT NULL,
  `PostNum` VARCHAR(20) NULL,
  `Status` VARCHAR(2) NULL,
  `StratDate` DATETIME NULL,
  `EndDate` DATETIME NULL,
  `PostWSCode` VARCHAR(20) NULL COMMENT '库存操作工作站编号',
  `PostEmpCode` VARCHAR(20) NULL COMMENT '库存操作员工编号',
  `PostType` VARCHAR(2) NULL COMMENT '出库类型\n1.正常-称重出库\n2.特殊-直接出库\n3.自动-由处理工作站发起自动生成出库交易信息',
  PRIMARY KEY (`PostHeaderId`))
ENGINE = InnoDB
COMMENT = '出库交易信息表';


-- -----------------------------------------------------
-- Table `MWRData`.`MWPostDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWPostDetail` (
  `PostDtlId` INT NOT NULL,
  `PostHeaderId` INT NULL,
  `CrateCode` VARCHAR(20) NULL,
  `PostNum` VARCHAR(20) NULL,
  `DepotCode` VARCHAR(20) NULL COMMENT '仓库编号',
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL,
  `WasteCode` VARCHAR(20) NULL,
  `InvWeight` FLOAT NULL,
  `PostWeight` FLOAT NULL,
  `Status` VARCHAR(2) NULL,
  `InvRecordId` INT NULL COMMENT '关联库存ID',
  `InvAuthId` INT NULL,
  PRIMARY KEY (`PostDtlId`))
ENGINE = InnoDB
COMMENT = '出库交易详情表';


-- -----------------------------------------------------
-- Table `MWRData`.`MWDestroyHeader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWDestroyHeader` (
  `DestHeaderId` INT NOT NULL,
  `DestNum` VARCHAR(20) NULL,
  `StratDate` DATETIME NULL,
  `EndDate` DATETIME NULL,
  `DestWSCode` VARCHAR(20) NULL,
  `DestEmpyCode` VARCHAR(20) NULL,
  `Status` VARCHAR(2) NULL,
  PRIMARY KEY (`DestHeaderId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWDestroyDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWDestroyDetail` (
  `DestroyDtlId` INT NOT NULL,
  `CrateCode` VARCHAR(20) NULL,
  `DestHeaderId` INT NULL,
  `DestNum` VARCHAR(20) NULL,
  `DepotCode` VARCHAR(20) NULL COMMENT '仓库编号',
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL,
  `WasteCode` VARCHAR(20) NULL,
  `PostWeight` FLOAT NULL,
  `DestWeight` FLOAT NULL,
  `Status` VARCHAR(2) NULL,
  `PostHeaderId` INT NULL,
  `InvRecordId` INT NULL COMMENT '关联库存ID',
  `InvAuthId` INT NULL,
  PRIMARY KEY (`DestroyDtlId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`SystemNextId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`SystemNextId` (
  `IdName` VARCHAR(50) NOT NULL,
  `MinValue` INT NULL,
  `Increment` INT NULL,
  `MaxValue` INT NULL,
  `IdValue` INT NULL,
  PRIMARY KEY (`IdName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`SysParameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`SysParameter` (
  `ParameterName` VARCHAR(128) NOT NULL,
  `ParameterValue` VARCHAR(128) NULL,
  `Remark` VARCHAR(45) NULL,
  PRIMARY KEY (`ParameterName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWInvAuthorizeAttach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInvAuthorizeAttach` (
  `InvAttachId` INT NOT NULL,
  `InvAuthId` INT NULL,
  `Path` VARCHAR(128) NULL,
  PRIMARY KEY (`InvAttachId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWInvAuthorize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInvAuthorize` (
  `InvAuthId` INT NOT NULL,
  `EmpyCode` VARCHAR(20) NULL,
  `Remark` VARCHAR(45) NULL,
  `EntryDate` DATETIME NULL,
  `DiffWeight` FLOAT NULL,
  PRIMARY KEY (`InvAuthId`))
ENGINE = InnoDB
COMMENT = '废品审核授权表-对有缺陷的废品进行人工审核授权记录，并记录附件';


-- -----------------------------------------------------
-- Table `MWRData`.`MWCarDispatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWCarDispatch` (
  `CarDisId` INT NOT NULL,
  `CarCode` VARCHAR(20) NULL,
  `OutDate` DATETIME NULL,
  `InDate` DATETIME NULL,
  PRIMARY KEY (`CarDisId`))
ENGINE = InnoDB
COMMENT = '车辆班次信息记录';


-- -----------------------------------------------------
-- Table `MWRData`.`SysLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`SysLog` (
  `LogId` INT NOT NULL,
  `Desc` VARCHAR(45) NULL,
  `Remark` TEXT NULL,
  `LogDate` DATETIME NULL,
  PRIMARY KEY (`LogId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWEmploy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWEmploy` (
  `EmpyId` INT NOT NULL,
  `EmpyCode` VARCHAR(20) NULL,
  `Name` VARCHAR(45) NULL,
  `UserGroupId` INT NULL,
  `EmpyType` VARCHAR(2) NULL,
  `UserName` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`EmpyId`))
ENGINE = InnoDB
COMMENT = '员工表-记录员工信息，以及员工用户组';


-- -----------------------------------------------------
-- Table `MWRData`.`MWUserGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWUserGroup` (
  `UserGroupId` INT NOT NULL,
  `GroupName` VARCHAR(45) NULL,
  PRIMARY KEY (`UserGroupId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWVendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWVendor` (
  `VendorId` INT NOT NULL,
  `Vendor` VARCHAR(45) NULL,
  `VendorCode` VARCHAR(20) NULL,
  `Address` VARCHAR(128) NULL,
  PRIMARY KEY (`VendorId`))
ENGINE = InnoDB
COMMENT = '供货商（医院）基础数据';


-- -----------------------------------------------------
-- Table `MWRData`.`MWFunction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWFunction` (
  `FuncTag` VARCHAR(45) NOT NULL,
  `FuncName` VARCHAR(45) NULL,
  PRIMARY KEY (`FuncTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWUserPermission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWUserPermission` (
  `id` INT NOT NULL,
  `UserGroupId` INT NULL,
  `FuncGroupId` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户权限表-记录用户组使用的功能';


-- -----------------------------------------------------
-- Table `MWRData`.`MWFunctionGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWFunctionGroup` (
  `FuncGroupId` INT NOT NULL,
  `FuncGroupName` VARCHAR(45) NULL,
  PRIMARY KEY (`FuncGroupId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWFunctionGroupDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWFunctionGroupDetail` (
  `FuncGroupDtlId` INT NOT NULL,
  `FuncGroupId` INT NULL,
  `FuncTag` VARCHAR(45) NULL,
  PRIMARY KEY (`FuncGroupDtlId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MWRData`.`MWCar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWCar` (
  `CarId` INT NOT NULL,
  `CarCode` VARCHAR(20) NULL,
  `Desc` VARCHAR(45) NULL,
  PRIMARY KEY (`CarId`))
ENGINE = InnoDB
COMMENT = '车辆基础数据';


-- -----------------------------------------------------
-- Table `MWRData`.`MWCrate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWCrate` (
  `CrateId` INT NOT NULL,
  `CrateCode` VARCHAR(20) NULL,
  `Desc` VARCHAR(45) NULL,
  `Status` VARCHAR(2) NULL,
  PRIMARY KEY (`CrateId`))
ENGINE = InnoDB
COMMENT = '货箱基础数据';


-- -----------------------------------------------------
-- Table `MWRData`.`MWDepot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWDepot` (
  `DepotId` INT NOT NULL,
  `Total` INT NULL,
  `Desc` VARCHAR(45) NULL,
  PRIMARY KEY (`DepotId`))
ENGINE = InnoDB
COMMENT = '库房基础数据';


-- -----------------------------------------------------
-- Table `MWRData`.`MWWasteCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWWasteCategory` (
  `CateId` INT NOT NULL,
  `WasteCode` VARCHAR(20) NULL,
  `Waste` VARCHAR(45) NULL,
  PRIMARY KEY (`CateId`))
ENGINE = InnoDB
COMMENT = '危险品种类数据';


-- -----------------------------------------------------
-- Table `MWRData`.`MWResidueInventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWResidueInventory` (
  `ResdInvId` INT NOT NULL,
  `InvWeight` FLOAT NULL,
  `EntryDate` DATETIME NULL,
  `RecoWSCode` VARCHAR(20) NULL,
  `RecoEmpyCode` VARCHAR(20) NULL,
  `HandlingType` VARCHAR(2) NULL COMMENT '处理方式',
  PRIMARY KEY (`ResdInvId`))
ENGINE = InnoDB
COMMENT = '残渣库存记录-记录残渣库存信息';


-- -----------------------------------------------------
-- Table `MWRData`.`MWInventoryLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MWRData`.`MWInventoryLog` (
  `InvLogId` INT NOT NULL,
  `WSCode` VARCHAR(20) NULL,
  `EmpyCode` VARCHAR(20) NULL,
  `OptType` VARCHAR(2) NULL COMMENT '操作类型',
  `OptDate` DATETIME NULL,
  `InvLogType` VARCHAR(2) NULL COMMENT '库存日志的类型 -废品出库，废品入库，残渣出库，残渣入库',
  `InvRecordId` INT NULL,
  PRIMARY KEY (`InvLogId`))
ENGINE = InnoDB
COMMENT = '库存处理日志-出入库存中操作的wscode empycode为最终库存操作者，本表中记录某个库存操作的变化的日志\n包括废品出库，废品入库，残渣出库，残渣入库';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
