-- MySQL Script generated by MySQL Workbench
-- 06/05/15 15:28:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cdcs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cdcs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdcs` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cdcs` ;

-- -----------------------------------------------------
-- Table `cdcs`.`bak_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdcs`.`bak_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `addtime` DATETIME NULL DEFAULT NULL,
  `opt_type` INT(11) NULL DEFAULT NULL,
  `opt_typename` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `num` DECIMAL(10,3) NULL DEFAULT NULL,
  `remark` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tmp1` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `_year` INT(11) NULL DEFAULT NULL,
  `_month` INT(11) NULL DEFAULT NULL,
  `_day` INT(11) NULL DEFAULT NULL,
  `province` INT(11) NULL DEFAULT NULL,
  `posttime` DATETIME NULL DEFAULT NULL,
  `Eleven_New_Col` VARCHAR(45) NULL,
  `Eleven_New_Col1` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdcs`.`bus_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdcs`.`bus_city` (
  `id` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `x_pos` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `y_pos` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `coords` VARCHAR(15000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `province` INT(50) NULL DEFAULT NULL,
  `provincename` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isok` INT(11) NULL DEFAULT NULL,
  `tmp1` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdcs`.`bus_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdcs`.`bus_data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cid` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `addtime` DATETIME NULL DEFAULT NULL,
  `opt_type` INT(11) NULL DEFAULT NULL,
  `opt_typename` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `num` DECIMAL(10,3) NULL DEFAULT NULL,
  `remark` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tmp1` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `_year` INT(11) NULL DEFAULT NULL,
  `_month` INT(11) NULL DEFAULT NULL,
  `_day` INT(11) NULL DEFAULT NULL,
  `province` INT(11) NULL DEFAULT NULL,
  `posttime` DATETIME NULL DEFAULT NULL,
  `Eleven_New_Col_int` INT NULL,
  `Eleven_New_Col_Str` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 199487
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdcs`.`sys_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdcs`.`sys_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `param_key` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `param_value` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isok` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cdcs`.`sys_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdcs`.`sys_user` (
  `loginname` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `username` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isok` INT(11) NULL DEFAULT NULL,
  `province` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`loginname`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
