-- MySQL Script generated by MySQL Workbench
-- 06/04/15 22:15:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema demodata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demodata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demodata` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `demodata` ;

-- -----------------------------------------------------
-- Table `demodata`.`demotable_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demodata`.`demotable_1` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ColStr` VARCHAR(45) NULL,
  `ColDecimal` DECIMAL(10,2) NULL,
  `newCol_1` VARCHAR(128) NULL,
  `newCol_2` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `demodata`.`demotable_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demodata`.`demotable_2` (
  `id` INT NOT NULL,
  `demotable_2col` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
